### ISSUE TITLE
conflicting LICENSE and COPYING.txt

### ISSUE THREAD

**Issue by fps** [ubi-agni/CBF#5]
There are different licenses in the files LICENSE and COPYING.txt. I'd be willing to relicence the original code under LGPL v3 as in copying.txt so we can clear this up.

Are you sure the used libraries do allow this change though?

**Comment by rhaschke** [comment]
@norro Arne, you added the LGPL v3 license when adding CPACK support.
Do you see any issues to update to LGPL v3? Personally, I don't mind.

**Comment by fps** [comment]
Just for completeness sake (even if being redundant, cause it's mabe obvious :)) I want to mention that the corresponding license snippets in all the headers would have to be adjusted, too. But this shouldn't be too hard to automate anyways..

**Comment by fps** [comment]
This is an (very likely incomplete) list of libraries CBF depends on. I guess we should check the respective licensing terms to decide if a relicensing to LGPLv3 is possible:

- boost: compatible afaict
- python C library: compatible afaict
- CPPAD (automatic differentiation package):  Eclipse Public License Version 1.0 , or the GNU General Public License Version 3.0. (possibly compatible)
- KDL:  GPL + runtime exception (would have to check - possible showstopper)
- XCF: hard to find ;)
- XRI: ?
- XMLTIO: 
- ActiveMemory
- Qt4/Qt5
- spacemouse
- Xerxes-C
- xmlstarlet
- XSDCXX: compatible iirc

The subject seems to be somewhat complex. If in doubt I'd say let's stick with the original license of GPL v2 or later which at the time I researched.
